# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	config.vm.box = "ubuntu/trusty64"
 	config.vm.synced_folder "../share", "/share"
 	config.vm.network :private_network, ip: "10.0.1.100"

	define_machine_name config, "vagrant-ubuntu"

end


def define_machine_name(config, name)
	config.vm.provider :virtualbox do |vbox|
		vbox.name = name
	end
end

