# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	config.vm.box = "%BOX%"
 	config.vm.synced_folder "../workspace", "/vagrant"
 	config.vm.network :private_network, ip: "%IP%"

	define_machine_name config, "%PROJECT_NAME%"

end


def define_machine_name(config, name)
	config.vm.provider :virtualbox do |vbox|
		vbox.name = name
	end
end

